### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by albeebe** [teltech/logger#13]
I find it to be annoying when i do this...

> log.Info("Hello World")

and see this in my console...

> {"severity":"INFO","eventTime":"2017-11-28T14:52:53-05:00","message":"Hello World","serviceContext":{"service":"test-service","version":"1.0"}}

when i would much rather see this...

> Hello World

**Comment by ShawnMilo** [comment]
A large part of the point of this is the structured logging. But you can use the standard library logger during development instead, if you want this output. It's even possible to use both together, but we probably shouldn't use the standard logger in production code.

**Comment by albeebe** [comment]
I just now took a look at the code and realized the library doesn't structure the data and send it to stackdriver via an API then output it to the console.  So i guess not much can be done.

**Comment by ShawnMilo** [comment]
No, the standard output and standard error from the application are directly consumed. I understand the confusion.
